{
 "title": "one bulb dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Main graph",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"light_data\")\r\n  |> range(start: -1h)\r\n  |> filter(fn: (r) => r._measurement == \"light_intensity\")\r\n  |> filter(fn: (r) => r._field == \"ldr\")\r\n  |> aggregateWindow(every: 1s, fn: mean)"
    }
   ]
  },
  {
   "title": "Latest value",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"light_data\")\r\n  |> range(start: -1h)\r\n  |> filter(fn: (r) => r._measurement == \"light_intensity\")\r\n  |> filter(fn: (r) => r._field == \"ldr\")\r\n  |> aggregateWindow(every: 1s, fn: mean)"
    }
   ]
  },
  {
   "title": "Real-time value",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"light_data\")\r\n  |> range(start: -1h)\r\n  |> filter(fn: (r) => r._measurement == \"light_intensity\")\r\n  |> filter(fn: (r) => r._field == \"ldr\")\r\n  |> aggregateWindow(every: 1s, fn: mean)"
    }
   ]
  },
  {
   "title": "Failure Probability (3d/7d/14d)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "query": "from(bucket: \"light_data\")\r\n  |> range(start: -6h)\r\n  |> filter(fn: (r) => r._measurement == \"ml_predictions\")\r\n  |> filter(fn: (r) => r._field == \"failure_prob_3d\" or r._field == \"failure_prob_7d\" or r._field == \"failure_prob_14d\")\r\n  |> aggregateWindow(every: 5m, fn: mean)"
    }
   ]
  },
  {
   "title": "Fault Type (Latest)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"light_data\")\r\n  |> range(start: -6h)\r\n  |> filter(fn: (r) => r._measurement == \"ml_predictions\")\r\n  |> filter(fn: (r) => r._field == \"fault_label\")\r\n  |> last()"
    }
   ]
  },
  {
   "title": "Alert Severity (Latest)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"light_data\")\r\n  |> range(start: -6h)\r\n  |> filter(fn: (r) => r._measurement == \"ml_predictions\")\r\n  |> filter(fn: (r) => r._field == \"severity\")\r\n  |> last()"
    }
   ]
  }
 ]
}